### PR TITLE
Updating dependencies to be able to compile again, plus various cleanups

### PR DESCRIPTION
**Pull request by arduano**
I came here after noticing that I can't build `dvm` on NixOS due to openssl issues. Turns out `dvm` depended on an old version of openssl via the dependency tree, meaning it can't compile on any rolling release distros anymore (including Arch, I tried).

I started with the `openssl` issue, and while upgrading all packages, I ended up having to fix many errors surrounding the CLI handling code (due to upgraded packages), so I cleaned everything up.

- Updated all packages, removed anything deprecated.
- Because of the above, `dvm` can now build on Arch and Nix again, as `dvm` depended on a deprecated verision of `openssl` through `reqwest`.
- Removed all aliases. They weren't documented anyway, and many were conflicting, e.g. `r` for `remove` and `run`.
- Removed duplicate command building code. The codebase had a derive-based and a builder-based command system, with the builder-based one being used purely for completions.
- Removed the list of constant strings. Many of them were replaced with `env!()` invocations, e.g. `env!("CARGO_PKG_VERSION")`, the rest I copied into their respective use sites.
- Renamed the `show` subcommand to `list`, as that's more commonly used in other CLI tools.
- Added a `LICENSE` file to reflect the `license` field in the `Cargo.toml` file.

I didn't bump the version number.

---

As a side note, I wouldn't mind taking over the maintenance of this project, as I regularly use it. My plan was to PR it into the Nix packages registry, but due to the openssl issue, I couldn't do that.

### CODE REVIEW

**Comment by diced** [comment]
I kinda just forgot about this, everything looks good to me! Also doesn't the license need to be changed, I think I will just add a gpl-3 license later

**Comment by arduano** [comment]
I've updated the license in the PR, is that ok? or should I revert that

**Comment by diced** [comment]
Yeah looks good, I'm gonna give it a build on my end and test it out, and merge once its all done. I'll also update the arch packages along with it :)

**Comment by diced** [comment]
AUR packages were updated like 2 hours ago, forgot to say

**Pull request merged**
